### ISSUE TITLE
Unittests not working?

### ISSUE THREAD

**Issue by sqtcyrus** [SpeQtral/etsi-qkd-api#4]
Running:
```bash
$ python -m unittest tests/test_helper.py
$ python -m unittest tests/test_kme.py 
```
and receiving several failures:

```bash
(venv) cproctor@spren:etsi-qkd-api>python -m unittest tests/test_helper.py 
.E...
======================================================================
ERROR: test_concat_keys (tests.test_helper.BasicHelperTest)
assume our test keys are = [123, 456, 789, 987, 654, 321], and we want to concat two keys at a time,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cproctor/code/interns/etsi-qkd-api/tests/test_helper.py", line 45, in test_concat_keys
    self.assertEqual(helper.concat_keys(keys_to_concat, 2), correct_answer)
TypeError: concat_keys() takes 1 positional argument but 2 were given

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=1)
(venv) cproctor@spren:etsi-qkd-api>python -m unittest tests/test_kme.py 
EEEE
======================================================================
ERROR: test_get_concat_key (tests.test_kme.BasicKmeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cproctor/code/interns/etsi-qkd-api/tests/test_kme.py", line 13, in setUp
    self.kme = KME('../key_files')
  File "/home/cproctor/code/interns/etsi-qkd-api/api/kme.py", line 67, in __init__
    self.crawl_keys()
  File "/home/cproctor/code/interns/etsi-qkd-api/api/kme.py", line 90, in crawl_keys
    file_path = os.path.join(self.key_file_path, filename)
  File "/usr/lib64/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

======================================================================
ERROR: test_get_multiple_keys (tests.test_kme.BasicKmeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cproctor/code/interns/etsi-qkd-api/tests/test_kme.py", line 13, in setUp
    self.kme = KME('../key_files')
  File "/home/cproctor/code/interns/etsi-qkd-api/api/kme.py", line 67, in __init__
    self.crawl_keys()
  File "/home/cproctor/code/interns/etsi-qkd-api/api/kme.py", line 90, in crawl_keys
    file_path = os.path.join(self.key_file_path, filename)
  File "/usr/lib64/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

======================================================================
ERROR: test_get_one_key (tests.test_kme.BasicKmeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cproctor/code/interns/etsi-qkd-api/tests/test_kme.py", line 13, in setUp
    self.kme = KME('../key_files')
  File "/home/cproctor/code/interns/etsi-qkd-api/api/kme.py", line 67, in __init__
    self.crawl_keys()
  File "/home/cproctor/code/interns/etsi-qkd-api/api/kme.py", line 90, in crawl_keys
    file_path = os.path.join(self.key_file_path, filename)
  File "/usr/lib64/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

======================================================================
ERROR: test_get_status (tests.test_kme.BasicKmeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cproctor/code/interns/etsi-qkd-api/tests/test_kme.py", line 13, in setUp
    self.kme = KME('../key_files')
  File "/home/cproctor/code/interns/etsi-qkd-api/api/kme.py", line 67, in __init__
    self.crawl_keys()
  File "/home/cproctor/code/interns/etsi-qkd-api/api/kme.py", line 90, in crawl_keys
    file_path = os.path.join(self.key_file_path, filename)
  File "/usr/lib64/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

----------------------------------------------------------------------
Ran 4 tests in 0.001s

FAILED (errors=4)
```

I didn't look into this but is this how the tests should be run?
Is there something else I might be missing?

Either way, let's make sure the unit tests are running as they should be.

**Comment by ajrheng** [comment]
Unittests should be run as simply ``python test_kme.py`` and ``python test_helper.py``. I have included basic instructions on running tests in the docs under the section ``Description of API``.
