### ISSUE TITLE
Appear to be missing dependencies for chat app

### ISSUE THREAD

**Issue by sqtcyrus** [SpeQtral/etsi-qkd-api#7]
An import of `Crypto` is occurring in [AES_class.py](https://github.com/SpeQtral/etsi-qkd-api/blob/7079467f73630e34353cebee16c32665a7214085/chat_app/AES_class.py#L7).

A point from when I was messing with a chat app:
* NOTE: `pycryptodomex` does not play well when byte compiling for Android      
* Install `pycryptodome` instead; it uses "Crypto" where domex uses "Cryptodome"

Not sure if relevant here but I installed `pycryptodome`.

Could put this into the [requirements.txt](https://github.com/SpeQtral/etsi-qkd-api/blob/7079467f73630e34353cebee16c32665a7214085/requirements.txt#L1) file.

Also, I may need to have a TLS cert bundle? I'm running:
```bash
$ python3 main.py
```
putting in 127.0.0.1 and "cyrus" and getting a segfault:
```bash
python3 main.py 
Traceback (most recent call last):
  File "/home/cproctor/code/interns/etsi-qkd-api/chat_app/connect_window.py", line 77, in start_chat_window
    self.chat_window = ChatWindow(self.other_ip_addr, self.your_username, self.other_username)
  File "/home/cproctor/code/interns/etsi-qkd-api/chat_app/chat_window.py", line 42, in __init__
    r = requests.get(url=URL, params=PARAMS, verify='/etc/ssl/certs/certA.pem')
  File "/home/cproctor/code/interns/etsi-qkd-api/venv/lib64/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/cproctor/code/interns/etsi-qkd-api/venv/lib64/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/cproctor/code/interns/etsi-qkd-api/venv/lib64/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cproctor/code/interns/etsi-qkd-api/venv/lib64/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/cproctor/code/interns/etsi-qkd-api/venv/lib64/python3.8/site-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/home/cproctor/code/interns/etsi-qkd-api/venv/lib64/python3.8/site-packages/requests/adapters.py", line 227, in cert_verify
    raise IOError("Could not find a suitable TLS CA certificate bundle, "
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/certA.pem
Aborted (core dumped)
```

I probably don't know what I'm doing to get it up and running. Some documentation would be helpful. Thanks!

**Comment by ajrheng** [comment]
The chat app is tested to work only for the chat-demo git branch. I will remove the chat_app folder from other branches to avoid future confusion. Apologies on my part.
